// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"gorm.io/gorm"
	"perfect-pic-server/internal/modules"
	repo3 "perfect-pic-server/internal/modules/image/repo"
	"perfect-pic-server/internal/modules/settings/repo"
	repo4 "perfect-pic-server/internal/modules/system/repo"
	repo2 "perfect-pic-server/internal/modules/user/repo"
	"perfect-pic-server/internal/platform/service"
	"perfect-pic-server/internal/router"
)

// Injectors from wire.go:

func InitializeApplication(gormDB *gorm.DB) (*Application, error) {
	settingStore := repo.NewSettingRepository(gormDB)
	appService := service.NewAppService(settingStore)
	userStore := repo2.NewUserRepository(gormDB)
	imageStore := repo3.NewImageRepository(gormDB)
	systemStore := repo4.NewSystemRepository(gormDB)
	appModules := modules.New(appService, userStore, imageStore, settingStore, systemStore)
	routerRouter := router.NewRouter(appModules, appService)
	application := NewApplication(appModules, routerRouter, appService)
	return application, nil
}
