// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"perfect-pic-server/internal/config"
	"perfect-pic-server/internal/db"
	"perfect-pic-server/internal/handler"
	"perfect-pic-server/internal/pkg/captcha"
	"perfect-pic-server/internal/pkg/redis"
	"perfect-pic-server/internal/repository"
	"perfect-pic-server/internal/router"
	"perfect-pic-server/internal/service"
	"perfect-pic-server/internal/usecase/admin"
	"perfect-pic-server/internal/usecase/app"
)

// Injectors from wire.go:

func InitializeApplication() (*Application, error) {
	gormDB, err := db.NewGormDB()
	if err != nil {
		return nil, err
	}
	settingStore := repository.NewSettingRepository(gormDB)
	dbConfig := config.NewDBConfig(settingStore)
	authService := service.NewAuthService(dbConfig)
	captchaCaptcha := captcha.NewCaptcha(dbConfig)
	userStore := repository.NewUserRepository(gormDB)
	client := redis.NewRedisClient()
	userService := service.NewUserService(userStore, dbConfig, client)
	emailService := service.NewEmailService(dbConfig)
	systemStore := repository.NewSystemRepository(gormDB)
	initService := service.NewInitService(systemStore, dbConfig)
	authUseCase := app.NewAuthUseCase(authService, userStore, userService, emailService, initService, dbConfig)
	passkeyStore := repository.NewPasskeyRepository(gormDB)
	passkeyService := service.NewPasskeyService(passkeyStore, dbConfig, client)
	passkeyUseCase := app.NewPasskeyUseCase(passkeyService, passkeyStore, authService, userStore)
	authHandler := handler.NewAuthHandler(authService, captchaCaptcha, authUseCase, initService, dbConfig, passkeyUseCase)
	imageStore := repository.NewImageRepository(gormDB)
	statUseCase := admin.NewStatUseCase(imageStore, userStore)
	systemHandler := handler.NewSystemHandler(initService, statUseCase, dbConfig, userService)
	settingsService := service.NewSettingsService(settingStore, dbConfig)
	settingsUseCase := admin.NewSettingsUseCase(emailService)
	settingsHandler := handler.NewSettingsHandler(settingsService, settingsUseCase)
	userUseCase := app.NewUserUseCase(userService, userStore, emailService, dbConfig)
	imageService := service.NewImageService(imageStore, dbConfig)
	userManageUseCase := admin.NewUserManageUseCase(userService, imageService, passkeyService)
	imageUseCase := app.NewImageUseCase(imageService, userService, userStore, dbConfig)
	userHandler := handler.NewUserHandler(userService, userUseCase, userManageUseCase, imageService, imageUseCase, authService, passkeyService, passkeyUseCase, client)
	imageHandler := handler.NewImageHandler(imageService, imageUseCase)
	routerRouter := router.NewRouter(authHandler, systemHandler, settingsHandler, userHandler, imageHandler, dbConfig, gormDB, client)
	application := NewApplication(routerRouter, dbConfig, gormDB, client)
	return application, nil
}
